/**
 * Combined A-team + B-team survey questions.
 * Each question is tagged with which team(s) need it.
 * All creators answer ALL questions so transfers don't require re-surveying.
 *
 * inputType: 'text' | 'textarea' | 'date' | 'number'
 */

export const SURVEY_QUESTIONS = [
  // ── Identity ──────────────────────────────────────────
  {
    key: 'of_username',
    text: 'OnlyFans username',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
    placeholder: 'e.g. yourusername (not your email)',
  },
  {
    key: 'nicknames',
    text: 'Any nicknames fans call you?',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
    required: true,
    placeholder: 'e.g. Cait, babe, princess',
  },
  {
    key: 'perceived_age',
    text: 'What age do your fans perceive you as?',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
    placeholder: 'e.g. 22',
  },
  {
    key: 'perceived_birthday',
    text: 'What birthday do you tell fans? (can be different from real)',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
    placeholder: 'e.g. March 15',
  },
  {
    key: 'zodiac_sign',
    text: 'Zodiac sign',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'perceived_origin',
    text: 'Where do fans think you\'re from?',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'perceived_location',
    text: 'Where do fans think you currently live?',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'recognition_source',
    text: 'How did most fans first discover you?',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'tattoo_count',
    text: 'How many tattoos do you have?',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'ethnicity',
    text: 'Ethnicity',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'languages',
    text: 'Languages you speak',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'height',
    text: 'Height',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'weight',
    text: 'Weight',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'physical_measurements',
    text: 'Physical measurements (if relevant to your content)',
    section: 'Identity',
    teamTag: ['A-team'],
    inputType: 'textarea',
  },
  {
    key: 'social_media_usernames',
    text: 'All your social media usernames (TikTok, Twitter, Reddit, etc.)',
    section: 'Identity',
    teamTag: ['Both'],
    inputType: 'textarea',
    autoFillFromAccounts: true,
    placeholder: 'This will be auto-filled from your Accounts step',
  },
  {
    key: 'fan_known_facts',
    text: 'Is there anything your fans may know about you from following you online that we should be aware of?',
    section: 'Identity',
    teamTag: ['Both'],
    inputType: 'textarea',
  },

  // ── Personality & Voice ───────────────────────────────
  {
    key: 'personality_3_words',
    text: 'How would you describe your personality in 3 words?',
    section: 'Personality & Voice',
    teamTag: ['Both'],
    inputType: 'text',
    placeholder: 'e.g. flirty, sweet, mysterious',
  },
  {
    key: 'chat_energy',
    text: 'What kind of energy do you want to project in your chats? (flirty, chill, sweet, mysterious, funny, confident, etc.)',
    section: 'Personality & Voice',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'fan_perception',
    text: 'How do you want fans to perceive you? (e.g., soft girl, confident queen, romantic dreamer, bold and playful)',
    section: 'Personality & Voice',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'morning_or_night',
    text: 'Are you a morning person or night person?',
    section: 'Personality & Voice',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'signature_phrases',
    text: 'Do you have any signature phrases or expressions?',
    section: 'Personality & Voice',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'texting_style',
    text: 'Do you have a specific texting style? (e.g., short messages, lowercase, lots of emojis, sweet tone)',
    section: 'Personality & Voice',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'text_abbreviations',
    text: 'Text abbreviations or slang you commonly use',
    section: 'Personality & Voice',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'common_emojis',
    text: 'Emojis you commonly use',
    section: 'Personality & Voice',
    teamTag: ['A-team'],
    inputType: 'text',
    hasEmojiPicker: true,
    placeholder: 'Click emojis below or type your own',
  },
  {
    key: 'subscriber_terms',
    text: 'What do you call your subscribers? (babe, love, daddy, etc.)',
    section: 'Personality & Voice',
    teamTag: ['A-team'],
    inputType: 'text',
    placeholder: 'e.g. babe, love, baby, handsome',
  },
  {
    key: 'representation',
    text: 'How would you describe what you represent in your own words?',
    section: 'Personality & Voice',
    teamTag: ['A-team'],
    inputType: 'textarea',
  },

  // ── Chat Style ────────────────────────────────────────
  {
    key: 'conversation_preference',
    text: 'Do you prefer deep conversations or light/fun ones?',
    section: 'Chat Style',
    teamTag: ['Both'],
    inputType: 'text',
  },
  {
    key: 'disliked_in_conversations',
    text: 'Three things you don\'t like in conversations',
    section: 'Chat Style',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'topics_to_avoid',
    text: 'Are there any topics you prefer to avoid? (politics, religion, personal life, etc.)',
    section: 'Chat Style',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'traits_to_highlight',
    text: 'Are there key traits or aspects of your personality that chatters should highlight?',
    section: 'Chat Style',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'messages_to_redirect',
    text: 'What type of messages or questions should chatters ignore or redirect?',
    section: 'Chat Style',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'prohibited_words',
    text: 'Are there any words or phrases you don\'t want used in chats?',
    section: 'Chat Style',
    teamTag: ['Both'],
    inputType: 'textarea',
    placeholder: 'e.g. "daddy", "sweetie", "hun" — anything that doesn\'t feel like you',
  },
  {
    key: 'prohibited_terminology',
    text: 'Any other prohibited terminology fans should never see?',
    section: 'Chat Style',
    teamTag: ['A-team'],
    inputType: 'textarea',
    placeholder: 'e.g. specific slang, pet names, or phrases that feel off-brand',
  },
  {
    key: 'workflow_notes',
    text: 'Is there anything specific the chatter should know about your workflow or chat dynamic?',
    section: 'Chat Style',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'additional_personal_facts',
    text: 'Any additional facts about yourself that would help chatters represent you accurately?',
    section: 'Chat Style',
    teamTag: ['A-team'],
    inputType: 'textarea',
  },

  // ── Content & Pricing ─────────────────────────────────
  {
    key: 'content_niche',
    text: 'What\'s your content niche?',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'content_abilities',
    text: 'What are you able/willing to do? (solo, B/G, G/G, customs, video calls, dildo, anal, etc.)',
    section: 'Content & Pricing',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'content_restrictions',
    text: 'Content restrictions — what will you NOT do?',
    section: 'Content & Pricing',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'limitations_instructions',
    text: 'Any other limitations and instructions for your chatters?',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'textarea',
  },
  {
    key: 'prohibited_topics',
    text: 'Prohibited communication topics (things chatters should never discuss)',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'textarea',
  },
  {
    key: 'sales_goals',
    text: 'Weekly/monthly sales goals',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'textarea',
  },
  {
    key: 'pricing_general',
    text: 'What is the average pricing you feel comfortable working with? (or describe your price list)',
    section: 'Content & Pricing',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'pricing_solo',
    text: 'Solo content pricing',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'pricing_bg_bb',
    text: 'B/G or B/B content pricing',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'pricing_joi',
    text: 'JOI video pricing',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'pricing_custom',
    text: 'Custom content pricing',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'pricing_underwear',
    text: 'Underwear / worn items pricing',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'pricing_cockrate',
    text: 'Cockrate pricing',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'pricing_followback',
    text: 'Social media followback price',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'pricing_phone',
    text: 'Phone number price',
    section: 'Content & Pricing',
    teamTag: ['A-team'],
    inputType: 'text',
  },

  // ── Favorites & Fun ───────────────────────────────────
  {
    key: 'favorite_food_drink_color',
    text: 'Favorite food / drink / color (for small talk)',
    section: 'Favorites & Fun',
    teamTag: ['Both'],
    inputType: 'text',
  },
  {
    key: 'favorite_movies_shows',
    text: 'What kind of movies or shows do you enjoy?',
    section: 'Favorites & Fun',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'favorite_music',
    text: 'Favorite music artist or band',
    section: 'Favorites & Fun',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'hobbies',
    text: 'What are your hobbies or things you love doing?',
    section: 'Favorites & Fun',
    teamTag: ['Both'],
    inputType: 'textarea',
  },
  {
    key: 'pets',
    text: 'Do you have pets? If so, what kind and what are their names?',
    section: 'Favorites & Fun',
    teamTag: ['Both'],
    inputType: 'text',
  },
  {
    key: 'dream_travel',
    text: 'Dream travel destination',
    section: 'Favorites & Fun',
    teamTag: ['Both'],
    inputType: 'text',
  },
  {
    key: 'favorite_animal',
    text: 'Favorite animal',
    section: 'Favorites & Fun',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'favorite_position',
    text: 'Favorite intimate position',
    section: 'Favorites & Fun',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'favorite_snack',
    text: 'Favorite snack',
    section: 'Favorites & Fun',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'favorite_holiday',
    text: 'Favorite holiday',
    section: 'Favorites & Fun',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'favorite_colors',
    text: 'Favorite colors',
    section: 'Favorites & Fun',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'weekend_preference',
    text: 'What do you prefer to do on weekends?',
    section: 'Favorites & Fun',
    teamTag: ['A-team'],
    inputType: 'text',
  },
  {
    key: 'fun_fact',
    text: 'Fun fact or something interesting about you that fans would love to know',
    section: 'Favorites & Fun',
    teamTag: ['Both'],
    inputType: 'textarea',
  },

  // ── Response Templates ────────────────────────────────
  {
    key: 'response_how_are_you',
    text: 'How would you typically respond to "How are you?"',
    section: 'Response Templates',
    teamTag: ['A-team'],
    inputType: 'textarea',
  },
  {
    key: 'response_what_are_you_up_to',
    text: 'How would you typically respond to "What are you up to?"',
    section: 'Response Templates',
    teamTag: ['A-team'],
    inputType: 'textarea',
  },
  {
    key: 'response_explicit',
    text: 'How would you respond to an explicit/forward message from a fan?',
    section: 'Response Templates',
    teamTag: ['A-team'],
    inputType: 'textarea',
  },
]

// Group questions by section for rendering
export function getQuestionsBySection() {
  const sections = {}
  for (const q of SURVEY_QUESTIONS) {
    if (!sections[q.section]) sections[q.section] = []
    sections[q.section].push(q)
  }
  return sections
}

// Section order for display
export const SECTION_ORDER = [
  'Identity',
  'Personality & Voice',
  'Chat Style',
  'Content & Pricing',
  'Favorites & Fun',
  'Response Templates',
]
