// Shared "mirror this Asset to Cloudflare" function.
//
// Single source of truth for the actual mirror work, used by:
//   • /api/admin/mirror-asset  — webhook called by Airtable Automations / Make
//   • lib/triggerMirror        — fire-and-forget invoked by upload routes
//   • cron sweeps              — backfill anything that slipped through
//
// What it does, given an Asset record ID:
//   • Photo asset + no CDN URL  → mirror image to Cloudflare Images
//   • Video asset + no Stream Raw ID → upload raw Dropbox link to CF Stream
//   • Video asset + edit + no Stream Edit ID → upload edit to CF Stream
//
// All side-effecty / network / Airtable PATCH work is wrapped in try/catch so
// a partial failure (e.g. raw upload succeeds, edit fails) still patches the
// part that worked. Idempotent: anything already mirrored is skipped via the
// "no CDN URL" / "no Stream * ID" guards.

import { fetchAirtableRecords } from '@/lib/adminAuth'
import {
  mirrorAssetToCloudflare,
  isCloudflareImagesConfigured,
} from '@/lib/cloudflareImages'
import {
  uploadVideoByUrl,
  isCloudflareStreamConfigured,
} from '@/lib/cloudflareStream'

const OPS_BASE = 'applLIT2t83plMqNx'
const ASSETS_TABLE = 'tblAPl8Pi5v1qmMNM'

function rawDropboxUrl(url) {
  if (!url) return ''
  const clean = url.replace(/[?&]dl=0/, '').replace(/[?&]raw=1/, '').replace(/[?&]dl=1/, '')
  return clean + (clean.includes('?') ? '&raw=1' : '?raw=1')
}

async function patchAsset(recordId, fields) {
  const res = await fetch(
    `https://api.airtable.com/v0/${OPS_BASE}/${ASSETS_TABLE}/${recordId}`,
    {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${process.env.AIRTABLE_PAT}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ fields }),
    }
  )
  if (!res.ok) throw new Error(`PATCH ${res.status}: ${await res.text()}`)
}

/**
 * Mirror an Asset to Cloudflare. Awaits all CF API calls (Stream copy + CF
 * Images upload return in seconds; transcode happens server-side at CF and
 * is NOT awaited).
 *
 * Returns a summary like {assetId, name, actions: [{step, ...}]}. Errors on
 * individual steps go in the summary; the function only throws on a fatal
 * lookup failure (asset not found, missing creds when expected).
 */
export async function mirrorAsset(assetId) {
  if (!assetId || typeof assetId !== 'string' || !assetId.startsWith('rec')) {
    throw new Error('assetId required (must start with rec...)')
  }

  const records = await fetchAirtableRecords(ASSETS_TABLE, {
    filterByFormula: `RECORD_ID()='${assetId}'`,
    fields: [
      'Asset Name', 'Asset Type', 'File Extension',
      'Dropbox Shared Link', 'Edited File Link', 'Thumbnail',
      'CDN URL', 'CDN Image ID',
      'Stream Edit ID', 'Stream Raw ID',
    ],
  })
  const asset = records[0]
  if (!asset) {
    throw new Error(`Asset ${assetId} not found`)
  }

  const f = asset.fields || {}
  const typeRaw = f['Asset Type']
  const type = (typeof typeRaw === 'string' ? typeRaw : typeRaw?.name || '').toLowerCase()
  const isVideo = type === 'video'
  const isImage = type === 'photo' || type === 'image' || (!type && /\.(jpe?g|png|gif|webp|heic|heif|bmp|tiff?)/i.test(f['Dropbox Shared Link'] || ''))

  const summary = { assetId, name: f['Asset Name'] || '', actions: [] }

  // ── Cloudflare Images: photos go direct, videos get a poster frame ───
  // Note: video poster extraction lives in the every-30-min cron because
  // it requires ffmpeg + downloading the video bytes (slow). The Stream
  // thumbnail (auto-generated by CF) takes over for video display anyway.
  if (isCloudflareImagesConfigured() && !f['CDN URL'] && isImage) {
    try {
      const result = await mirrorAssetToCloudflare(asset)
      summary.actions.push({ step: 'cf-images', ...result })
    } catch (err) {
      summary.actions.push({ step: 'cf-images', error: err.message })
    }
  }

  // ── Cloudflare Stream for videos ─────────────────────────────────────
  if (isVideo && isCloudflareStreamConfigured()) {
    const updates = {}

    if (f['Edited File Link'] && !f['Stream Edit ID']) {
      try {
        const { uid } = await uploadVideoByUrl(rawDropboxUrl(f['Edited File Link']), {
          airtableId: asset.id, kind: 'edit',
        })
        updates['Stream Edit ID'] = uid
        summary.actions.push({ step: 'stream-edit', uid })
      } catch (err) {
        summary.actions.push({ step: 'stream-edit', error: err.message })
      }
    }

    if (f['Dropbox Shared Link'] && !f['Stream Raw ID']) {
      try {
        const { uid } = await uploadVideoByUrl(rawDropboxUrl(f['Dropbox Shared Link']), {
          airtableId: asset.id, kind: 'raw',
        })
        updates['Stream Raw ID'] = uid
        summary.actions.push({ step: 'stream-raw', uid })
      } catch (err) {
        summary.actions.push({ step: 'stream-raw', error: err.message })
      }
    }

    if (Object.keys(updates).length) {
      try {
        await patchAsset(asset.id, updates)
      } catch (err) {
        summary.actions.push({ step: 'airtable-patch', error: err.message })
      }
    }
  }

  return summary
}
