export const dynamic = 'force-dynamic'
export const maxDuration = 30

import { requireAdminOrEditor } from '@/lib/adminAuth'
import { getDropboxAccessToken, getDropboxThumbnailFromLink } from '@/lib/dropbox'

// Returns a JPEG thumbnail for a Dropbox shared-link image, generated by
// Dropbox's get_thumbnail_v2 endpoint. The reason this exists: HEIC/HEIF
// images don't render in Chrome or Firefox (only Safari has native HEIC),
// so iPhone photos uploaded raw show as broken-image icons in the picker.
// Dropbox's thumbnail API produces a JPEG from any image format including
// HEIC, so we proxy through here for non-browser-native formats.
//
// Cached aggressively at the CDN edge — thumbnails are deterministic per
// shared link and the Dropbox link itself is the cache key.

export async function GET(request) {
  try { await requireAdminOrEditor() } catch (e) { return e }

  const { searchParams } = new URL(request.url)
  const url = searchParams.get('url')
  const size = searchParams.get('size') || 'w480h480'
  if (!url) {
    return new Response(JSON.stringify({ error: 'url required' }), {
      status: 400, headers: { 'Content-Type': 'application/json' },
    })
  }

  try {
    const accessToken = await getDropboxAccessToken()
    const buffer = await getDropboxThumbnailFromLink(accessToken, url, { size })
    return new Response(buffer, {
      status: 200,
      headers: {
        'Content-Type': 'image/jpeg',
        // Long cache — same shared link always produces same thumbnail
        'Cache-Control': 'public, max-age=86400, s-maxage=86400, immutable',
      },
    })
  } catch (err) {
    console.error('[dropbox-thumbnail] error:', err.message)
    return new Response(JSON.stringify({ error: err.message }), {
      status: 502, headers: { 'Content-Type': 'application/json' },
    })
  }
}
