export const dynamic = 'force-dynamic'
// Pull-from-URL Stream upload returns the UID in <2s; CF Images upload-from-
// URL is similar; ffmpeg poster extract for videos can take 15s. Pad for
// slow Dropbox fetches and a safety margin under the Pro plan ceiling.
export const maxDuration = 60

import { NextResponse } from 'next/server'
import { fetchAirtableRecords } from '@/lib/adminAuth'
import {
  mirrorAssetToCloudflare,
  isCloudflareImagesConfigured,
} from '@/lib/cloudflareImages'
import {
  uploadVideoByUrl,
  isCloudflareStreamConfigured,
} from '@/lib/cloudflareStream'

const OPS_BASE = 'applLIT2t83plMqNx'
const ASSETS_TABLE = 'tblAPl8Pi5v1qmMNM'

function rawDropboxUrl(url) {
  if (!url) return ''
  const clean = url.replace(/[?&]dl=0/, '').replace(/[?&]raw=1/, '').replace(/[?&]dl=1/, '')
  return clean + (clean.includes('?') ? '&raw=1' : '?raw=1')
}

async function patchAsset(recordId, fields) {
  const res = await fetch(
    `https://api.airtable.com/v0/${OPS_BASE}/${ASSETS_TABLE}/${recordId}`,
    {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${process.env.AIRTABLE_PAT}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ fields }),
    }
  )
  if (!res.ok) throw new Error(`PATCH ${res.status}: ${await res.text()}`)
}

/**
 * POST /api/admin/mirror-asset
 *
 * Webhook endpoint to mirror a single Asset to Cloudflare immediately —
 * skipping the every-15-min cron lag. Wired up via Airtable Automation
 * ("when record created in Assets, send webhook here") or by adding an
 * HTTP step to the Make.com Dropbox-ingest scenario.
 *
 * Auth: pass `?secret=<MIRROR_WEBHOOK_SECRET>` as a query param. Same
 * pattern as the cron endpoints — keeps random outsiders from triggering
 * CF API calls on our dime.
 *
 * Body OR query: { assetId: "rec..." }
 *
 * What it does, based on the asset type:
 *   - Photo → Cloudflare Images (the photo itself)
 *   - Video → both:
 *       (a) ffmpeg-extract a poster frame → Cloudflare Images (asset.cdnUrl)
 *       (b) Stream upload of edited file (if any) and raw clip
 *
 * Idempotent — anything already mirrored is skipped via the existing
 * "already has CDN URL / Stream UID" checks in the underlying helpers.
 *
 * Returns a small summary so Make / Airtable / your test curl can see
 * what happened. Does NOT wait for Stream transcoding to finish (that's
 * server-side at CF and takes longer than any reasonable webhook timeout).
 */
export async function POST(request) {
  // Auth via query secret — same pattern as `?secret=` on cron callback URLs.
  const expectedSecret = process.env.MIRROR_WEBHOOK_SECRET || process.env.CRON_SECRET
  const { searchParams } = new URL(request.url)
  const providedSecret = searchParams.get('secret') || request.headers.get('x-mirror-secret')
  if (expectedSecret && providedSecret !== expectedSecret) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // Accept the assetId from query OR body — easier to wire from any source.
  let body = {}
  try { body = await request.json() } catch {}
  const assetId = searchParams.get('id') || searchParams.get('assetId') || body.assetId || body.id
  if (!assetId || typeof assetId !== 'string' || !assetId.startsWith('rec')) {
    return NextResponse.json({ error: 'assetId required (must start with rec...)' }, { status: 400 })
  }

  // Pull the Asset record once, with all the fields any of the mirror
  // helpers might need.
  const records = await fetchAirtableRecords(ASSETS_TABLE, {
    filterByFormula: `RECORD_ID()='${assetId}'`,
    fields: [
      'Asset Name', 'Asset Type', 'File Extension',
      'Dropbox Shared Link', 'Edited File Link', 'Thumbnail',
      'CDN URL', 'CDN Image ID',
      'Stream Edit ID', 'Stream Raw ID',
    ],
  })
  const asset = records[0]
  if (!asset) {
    return NextResponse.json({ error: `Asset ${assetId} not found` }, { status: 404 })
  }

  const f = asset.fields || {}
  const typeRaw = f['Asset Type']
  const type = (typeof typeRaw === 'string' ? typeRaw : typeRaw?.name || '').toLowerCase()
  const isVideo = type === 'video'
  const isImage = type === 'photo' || type === 'image' || (!type && /\.(jpe?g|png|gif|webp|heic|heif|bmp|tiff?)/i.test(f['Dropbox Shared Link'] || ''))

  const summary = { assetId, name: f['Asset Name'] || '', actions: [] }

  // ── Cloudflare Images: photos go direct, videos get a poster frame ───
  if (isCloudflareImagesConfigured() && !f['CDN URL']) {
    if (isImage) {
      const result = await mirrorAssetToCloudflare(asset)
      summary.actions.push({ step: 'cf-images', ...result })
    }
    // Note: video poster extraction is left to the hourly cron, since it
    // requires ffmpeg + downloading the video bytes (slow, blocks this
    // webhook response). The Stream thumbnail (auto-generated by CF) takes
    // over for video display anyway.
  }

  // ── Cloudflare Stream for videos: kick raw + edit uploads ────────────
  if (isVideo && isCloudflareStreamConfigured()) {
    const updates = {}

    if (f['Edited File Link'] && !f['Stream Edit ID']) {
      try {
        const { uid } = await uploadVideoByUrl(rawDropboxUrl(f['Edited File Link']), {
          airtableId: asset.id, kind: 'edit',
        })
        updates['Stream Edit ID'] = uid
        summary.actions.push({ step: 'stream-edit', uid })
      } catch (err) {
        summary.actions.push({ step: 'stream-edit', error: err.message })
      }
    }

    if (f['Dropbox Shared Link'] && !f['Stream Raw ID']) {
      try {
        const { uid } = await uploadVideoByUrl(rawDropboxUrl(f['Dropbox Shared Link']), {
          airtableId: asset.id, kind: 'raw',
        })
        updates['Stream Raw ID'] = uid
        summary.actions.push({ step: 'stream-raw', uid })
      } catch (err) {
        summary.actions.push({ step: 'stream-raw', error: err.message })
      }
    }

    if (Object.keys(updates).length) {
      try {
        await patchAsset(asset.id, updates)
      } catch (err) {
        summary.actions.push({ step: 'airtable-patch', error: err.message })
      }
    }
  }

  return NextResponse.json({ ok: true, ...summary })
}

// GET handler is the same — some webhook providers (Airtable Automations
// included) default to GET. Same auth, same args, same behavior.
export const GET = POST
